- hosts: "*"
  become: yes
  tasks:
    - name: Update apt and upgrade all packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
        - python3-venv
        - python3-dev
        - build-essential
        - libssl-dev
        - libffi-dev
        - python3-setuptools
        - python3-wheel
        - python3-cffi
        - python3-pycparser
        - python3-apt